spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # none / validate / update / create / create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true   # 콘솔에 SQL 출력
        dialect: org.hibernate.dialect.MySQL8Dialect